[project]
name = "anchor-tasking-management-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pablo Martínez Prado", email = "pablo.martinezprado@outlook.es" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "requests>=2.34.2",
    "typer>=0.27.2",
]

[project.scripts]
anchor-tasking-management-cli = "anchor_tasking_management_cli:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
